ssl_verify_client_exception: fixed segfault of referring null pointer
import bugfix of nginx core phase from this nginx commit:

```
commit 57dde2ab37708423d97333be19830437732b3f4f
Author: Sergey Kandaurov <pluknet@nginx.com>
Date:   Tue Jan 30 17:46:31 2018 +0300

    SSL: using default server context in session remove (closes #1464).

    This fixes segfault in configurations with multiple virtual servers sharing
    the same port, where a non-default virtual server block misses certificate.
```